# -*- coding: utf-8 -*-
#
# SeFEF documentation build configuration file

import sys
import os
import re

sys.path.insert(0, os.path.abspath("."))
sys.path.insert(0, os.path.abspath("../"))

# To be able to import to ReadTheDocs
# from mock import Mock as MagicMock


# class Mock(MagicMock):
#     @classmethod
#     def __getattr__(cls, name):
#             return Mock()


# MOCK_MODULES = ['biosppy', 'h5py', 'matplotlib', 'numpy','pandas',
#                 'plotly', 'plotly.graph_objects', 'pyarrow',
#                 'scipy', 'scipy.signal', 'scipy.stats',
#                 'scipy.fft', 'sklearn', 'sklearn.metrics']

# sys.modules.update((mod_name, Mock()) for mod_name in MOCK_MODULES)

# -- General configuration ------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.coverage',
    'sphinx.ext.viewcode',
    'sphinx.ext.napoleon',
    'sphinx.ext.imgmath',
]

# Napoleon settings
napoleon_use_rtype = False

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
# source_suffix = ['.rst', '.md']
source_suffix = {'.rst': 'restructuredtext'}


# The master toctree document.
master_doc = 'index'

# General information about the project.
project = 'SeFEF'
copyright = '2024, Ana Sofia Carmo'
author = 'Ana Sofia Carmo'

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
# Extract version from setup.py
with open('../setup.py', 'r') as f:
    setup_content = f.read()

version_match = re.search(r"version=['\"]([^'\"]+)['\"]", setup_content)
if version_match:
    release = version_match.group(1)  # Full version
    version = ".".join(release.split(".")[:2])  # Short version (major.minor)
else:
    release = version = "unknown"


# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'en'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns = ['_build']

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'


# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False


# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
html_theme = 'sphinx_rtd_theme'

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
html_theme_options = {
    'logo_only': True,
}


# The name of an image file (relative to this directory) to place at the top
# of the sidebar.
html_logo = "logo/sefef-logo.png"

# The name of an image file (within the static path) to use as favicon of the
# docs.  This file should be a Windows icon file (.ico) being 16x16 or 32x32
# pixels large.
html_favicon = "logo/sefef-icon.ico"


# If true, links to the reST sources are added to the pages.
html_show_sourcelink = False


htmlhelp_basename = 'SeFEFdoc'

# -- Options for LaTeX output ---------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    # 'papersize': 'letterpaper',

    # The font size ('10pt', '11pt' or '12pt').
    # 'pointsize': '10pt',

    # Additional stuff for the LaTeX preamble.
    # 'preamble': '',

    # Latex figure (float) alignment
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, 'SeFEF.tex', 'SeFEF Documentation',
     'Ana Sofia Carmo', 'manual'),
]


# -- Options for manual page output ---------------------------------------

man_pages = [
    (master_doc, 'sefef', 'SeFEF Documentation',
     [author], 1)
]


# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, 'SeFEF', 'SeFEF Documentation',
     author, 'SeFEF', 'Seizure Forecasting Evaluation Framework.',
     'Miscellaneous'),
]
